spring:
  datasource:
    username: root
    initialization-mode: never
    url: jdbc:mysql://localhost:3306/todo
    #    data: classpath:/data.sql
    password: '@Jesi9520'
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    com:
      tutorial:
        spring-boot: DEBUG
  path: logs